Change font
qbittorrent/qBittorrent-website pull request #228
Opened 2024-06-30 11:10 UTC by rivercory

Changed font and replaced it with a modern design.

2024-07-03 06:18 UTC, rivercory commented
@sledgehammer999 Please review my PR 😢

2024-07-03 06:43 UTC, Chocobo1 requested changes

2024-07-03 06:43 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
We intentionally prohibit linking to 3rd party resources, to avoid user tracking. This cannot be done like this.

2024-07-03 06:45 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
If so, should I change that to a local file?

2024-07-03 06:49 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
I don't mind. But is it really worth it? Is it much better than the universal fonts?

2024-07-03 06:50 UTC, Chocobo1 commented on _site/css/TLbanner.css
> +}
Doesn't do what the commit is describing. Move it to its own commit.

2024-07-03 06:51 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Sure! When I tested it, the readability was greatly improved.

2024-07-03 06:51 UTC, rivercory commented on _site/css/TLbanner.css
> +}
Okay

2024-07-03 06:51 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
If possible, could you provide a comparison screenshot?

2024-07-03 14:34 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
- Before
![2024-07-03 23 33 36 www qbittorrent org 297a425cfbd3](https://github.com/qbittorrent/qBittorrent-website/assets/116472903/d121608f-b24e-4175-a623-d84e26f88ace)
- After
![2024-07-03 23 33 06 localhost fef85aa558d9](https://github.com/qbittorrent/qBittorrent-website/assets/116472903/7b5870fa-749d-4347-9ae8-3ba509f2d304)

2024-07-04 12:04 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
@Chocobo1 What do you think?

2024-07-06 08:15 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
It's different... but I don't think it is better.

2024-07-06 08:16 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Why?

2024-07-06 08:17 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
I don't like the new style.

2024-07-06 08:19 UTC, rivercory commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Please explain in detail why you don't like it. Don't you like the readability? Or doesn't match the style of the project?

2024-07-06 08:21 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
The font for TLbanner.css could be changed with another but I'll prefer using builtin fonts. If all of the builtin fonts are not good then I won't bother with a 3rd party font. It doesn't seems significant enough to add another resource just for it.

2024-07-06 08:24 UTC, Chocobo1 commented on _site/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Another thing. I noticed the characters have larger vertical spacing and I think it is nice.
Everything else doesn't look good.

2024-07-06 09:57 UTC, closed without merging