Fix release news typos
qbittorrent/qBittorrent-website pull request #229
Opened 2024-10-04 15:31 UTC by Kissaki

Fix two 'was release' -> 'was released' typos.

Earlier release news do not have this typo.

2024-10-08 05:07 UTC, Chocobo1 commented
File `_site/news_feed.atom` should also be regenerated.

2024-10-10 17:07 UTC, Chocobo1 requested changes

2024-10-10 17:07 UTC, Chocobo1 commented on _site/news_feed.atom
@Kissaki 
You should not edit `_site/news_feed.atom` by hand and instead follow the instructions in README.md to build it.

2024-10-12 09:03 UTC, Kissaki commented on _site/news_feed.atom
Can you run it? I don't have npm installed, and don't intend to.

2024-10-12 09:04 UTC, Kissaki commented on _site/news_feed.atom
I'm surprised the transformation is even committed. Why is it not only the sources, and CI builds and publishes the result?

2024-10-12 09:05 UTC, Kissaki commented on _site/news_feed.atom
CI could also build and commit the changes.

2024-10-13 12:43 UTC, Kissaki commented on _site/news_feed.atom
I generated them with deno v2.

2024-10-15 07:24 UTC, merged

2024-10-15 07:25 UTC, Chocobo1 commented
@Kissaki 
Thank you!